try to specify more types explicitly
martin@labolg ~/stage/cl-cpp-generator2/example/33_copernicus_gtk/source $ make
c++ -c -o vis_04_decode_packet.o vis_04_decode_packet.cpp -Os -g3 -ggdb -Wall -Wextra -Werror -Wshadow -Wdouble-promotion -fno-common -Wconversion -ffunction-sections -fdata-sections -Wno-error=unused-variable -pipe `pkg-config gtkmm-3.0 --cflags` -march=native -mtune=native
vis_04_decode_packet.cpp: In function 'int init_decode_packet(int, std::complex<float>*)':
vis_04_decode_packet.cpp:555:38: error: catching polymorphic type 'class std::out_of_range' by value [-Werror=catch-value=]
  555 |           } catch (std::out_of_range e) {
      |                                      ^
vis_04_decode_packet.cpp:586:49: error: conversion from 'float' to 'std::array<const float, 4>::size_type' {aka 'long unsigned int'} may change value [-Werror=float-conversion]
  586 |             v = ((symbol_sign) * (table_nrl0.at(mcode)) * (table_sf.at(thidx)));
      |                                                 ^~~~~
vis_04_decode_packet.cpp:587:38: error: catching polymorphic type 'class std::out_of_range' by value [-Werror=catch-value=