can't force linking with static ffmpeg libaries
 CMakeFiles/cxxnet_client.dir/src/VideoArchiveImpl.cpp.o CMakeFiles/cxxnet_client.dir/src/VideoDecoder.cpp.o CMakeFiles/cxxnet_client.dir/src/DurationComputer.cpp.o CMakeFiles/cxxnet_client.dir/proto/video.capnp.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/capnp/c++.capnp.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/capnp/blob.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/capnp/arena.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/capnp/layout.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/capnp/list.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/capnp/any.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/capnp/message.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/capnp/schema.capnp.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/capnp/stream.capnp.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/capnp/serialize.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/capnp/serialize-packed.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/capnp/schema.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/capnp/schema-loader.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/capnp/dynamic.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/capnp/stringify.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/capnp/serialize-async.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/capnp/capability.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/capnp/membrane.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/capnp/dynamic-capability.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/capnp/rpc.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/capnp/rpc.capnp.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/capnp/rpc-twoparty.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/capnp/rpc-twoparty.capnp.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/capnp/persistent.capnp.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/capnp/ez-rpc.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/kj/array.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/kj/cidr.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/kj/list.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/kj/common.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/kj/debug.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/kj/exception.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/kj/io.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/kj/memory.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/kj/mutex.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/kj/string.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/kj/source-location.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/kj/hash.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/kj/table.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/kj/thread.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/kj/main.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/kj/arena.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/kj/test-helpers.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/kj/units.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/kj/encoding.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/kj/refcount.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/kj/string-tree.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/kj/time.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/kj/filesystem.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/kj/filesystem-disk-unix.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/kj/parse/char.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/kj/async.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/kj/async-unix.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/kj/async-io.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/kj/async-io-unix.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/capnproto/c++/src/kj/timer.c++.o CMakeFiles/cxxnet_client.dir/home/martin/src/avcpp/src/audioresampler.cpp.o CMakeFiles/cxxnet_client.dir/home/martin/src/avcpp/src/averror.cpp.o CMakeFiles/cxxnet_client.dir/home/martin/src/avcpp/src/avtime.cpp.o CMakeFiles/cxxnet_client.dir/home/martin/src/avcpp/src/avutils.cpp.o CMakeFiles/cxxnet_client.dir/home/martin/src/avcpp/src/channellayout.cpp.o CMakeFiles/cxxnet_client.dir/home/martin/src/avcpp/src/codec.cpp.o CMakeFiles/cxxnet_client.dir/home/martin/src/avcpp/src/codeccontext.cpp.o CMakeFiles/cxxnet_client.dir/home/martin/src/avcpp/src/codecparameters.cpp.o CMakeFiles/cxxnet_client.dir/home/martin/src/avcpp/src/dictionary.cpp.o CMakeFiles/cxxnet_client.dir/home/martin/src/avcpp/src/filters/buffersink.cpp.o CMakeFiles/cxxnet_client.dir/home/martin/src/avcpp/src/filters/buffersrc.cpp.o CMakeFiles/cxxnet_client.dir/home/martin/src/avcpp/src/filters/filter.cpp.o CMakeFiles/cxxnet_client.dir/home/martin/src/avcpp/src/filters/filtercontext.cpp.o CMakeFiles/cxxnet_client.dir/home/martin/src/avcpp/src/filters/filtergraph.cpp.o CMakeFiles/cxxnet_client.dir/home/martin/src/avcpp/src/filters/filterpad.cpp.o CMakeFiles/cxxnet_client.dir/home/martin/src/avcpp/src/format.cpp.o CMakeFiles/cxxnet_client.dir/home/martin/src/avcpp/src/formatcontext.cpp.o CMakeFiles/cxxnet_client.dir/home/martin/src/avcpp/src/frame.cpp.o CMakeFiles/cxxnet_client.dir/home/martin/src/avcpp/src/packet.cpp.o CMakeFiles/cxxnet_client.dir/home/martin/src/avcpp/src/pixelformat.cpp.o CMakeFiles/cxxnet_client.dir/home/martin/src/avcpp/src/rational.cpp.o CMakeFiles/cxxnet_client.dir/home/martin/src/avcpp/src/rect.cpp.o CMakeFiles/cxxnet_client.dir/home/martin/src/avcpp/src/sampleformat.cpp.o CMakeFiles/cxxnet_client.dir/home/martin/src/avcpp/src/stream.cpp.o CMakeFiles/cxxnet_client.dir/home/martin/src/avcpp/src/timestamp.cpp.o CMakeFiles/cxxnet_client.dir/home/martin/src/avcpp/src/videorescaler.cpp.o -o cxxnet_client  -ldrm  -lva  -lva-drm  -lva-x11  -ldav1d  -lopus  -lx264  -lX11  -lxcb  -lxcb-shm  -lxcb-shape  -lxcb-xfixes  -lpulse  -lXv  -lXext  -lXfixes  -lX11-xcb  -lxcb-dri3  -lXdmcp  -lpulsecommon-17.0  -lsndfile  -lsystemd  -lasyncns  -lFLAC  -lvorbis  -lvorbisenc  -logg  -lmpg123  -lmp3lame  -lcap  -lmvec  /usr/lib64/libavformat.a  -lavformat  /usr/lib64/libavutil.a  -lavutil && :
/usr/lib/gcc/x86_64-pc-linux-gnu/14/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/libavformat.a(avidec.o): undefined reference to symbol 'avpriv_find_start_code@@LIBAVCODEC_60'
/usr/lib/gcc/x86_64-pc-linux-gnu/14/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/libavcodec.so.60: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status