the break isn't placed properly
In file included from simple_00_client.hpp:17,
                 from simple_00_client.cpp:16:
vis_03_connection.hpp: In lambda function:
vis_03_connection.hpp:272:31: error: expected ‘;’ before ‘break’
  272 |             write_validation() break;
      |                               ^~~~~~
      |                               ;
compilation terminated due to -Wfatal-errors.
make: *** [makefile:39: simple_00_client.o] Error 1