get rid of a few more conversion warnings
c++ -c -o vis_07_decode_type_c_packet.o vis_07_decode_type_c_packet.cpp -Os -g3 -ggdb -Wall -Wextra -Werror -Wshadow -Wdouble-promotion -fno-common -Wconversion -ffunction-sections -fdata-sections -Wno-error=unused-variable -pipe `pkg-config gtkmm-3.0 --cflags` -march=native -mtune=native
vis_07_decode_type_c_packet.cpp:26:6: error: conversion from 'double' to 'float' changes value from '6.6000000000000003e-2' to '6.59999996e-2f' [-Werror=float-conversion]
   26 |     (6.60e-2),  (0.19850f), (0.3320f),  (0.46770f), (0.60610f), (0.74870f),
      |     ~^~~~~~~~