what is wrong now?
martin@labolg ~/stage/cl-cpp-generator2/example/41_gtk3_popover/source $ make
c++ -c -o vis_03_treeview_with_popup.o vis_03_treeview_with_popup.cpp -O2 -std=gnu++20 -Wall -Wextra -Werror -Wshadow -Wdouble-promotion -fno-common -Wconversion -ffunction-sections -fdata-sections -Wno-error=inaccessible-base -Wno-error=unused-variable -Wno-error=unused-parameter -Wno-error=double-promotion -pipe `pkg-config gtkmm-3.0 --cflags` -march=native -mtune=native
In file included from /usr/include/sigc++-2.0/sigc++/functors/slot.h:7,
                 from /usr/include/sigc++-2.0/sigc++/signal_base.h:27,
                 from /usr/include/sigc++-2.0/sigc++/signal.h:8,
                 from /usr/include/sigc++-2.0/sigc++/sigc++.h:104,
                 from /usr/include/glibmm-2.4/glibmm/thread.h:50,
                 from /usr/include/glibmm-2.4/glibmm.h:88,
                 from /usr/include/gtkmm-3.0/gtkmm.h:87,
                 from vis_03_treeview_with_popup.hpp:11,
                 from vis_03_treeview_with_popup.cpp:11:
/usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h: In instantiation of 'sigc::adaptor_functor<T_functor>::adaptor_functor(const T_functor&) [with T_functor = TreeView_WithPopup]':
/usr/include/sigc++-2.0/sigc++/functors/slot.h:67:58:   required from 'sigc::internal::typed_slot_rep<T_functor>::typed_slot_rep(const T_functor&) [with T_functor = TreeView_WithPopup]'
/usr/include/sigc++-2.0/sigc++/functors/slot.h:546:17:   required from 'sigc::slot0<T_return>::slot0(const T_functor&) [with T_functor = TreeView_WithPopup; T_return = void]'
/usr/include/sigc++-2.0/sigc++/functors/slot.h:1774:26:   required from 'sigc::slot<T_return, sigc::nil, sigc::nil, sigc::nil, sigc::nil, sigc::nil, sigc::nil, sigc::nil>::slot(const T_functor&) [with T_functor = TreeView_WithPopup; T_return = void]'
vis_03_treeview_with_popup.cpp:36:63:   required from here
/usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:237:26: error: use of deleted function 'TreeView_WithPopup::TreeView_WithPopup(const TreeView_WithPopup&)'
  237 |     : functor_(_A_functor)
      |                          ^
In file included from vis_03_treeview_with_popup.cpp:11:
vis_03_treeview_with_popup.hpp:16:7: note: 'TreeView_WithPopup::TreeView_WithPopup(const TreeView_WithPopup&)' is implicitly deleted because the default definition would be ill-formed:
   16 | class TreeView_WithPopup : public Gtk::TreeView {
      |       ^~~~~~~~~~~~~~~~~~
vis_03_treeview_with_popup.hpp:16:7: error: use of deleted function 'Gtk::TreeView::TreeView(const Gtk::TreeView&)'
In file included from /usr/include/gtkmm-3.0/gtkmm/combobox.h:33,
                 from /usr/include/gtkmm-3.0/gtkmm/appchooserbutton.h:27,
                 from /usr/include/gtkmm-3.0/gtkmm.h:107,
                 from vis_03_treeview_with_popup.hpp:11,
                 from vis_03_treeview_with_popup.cpp:11:
/usr/include/gtkmm-3.0/gtkmm/treeview.h:226:3: note: declared here
  226 |   TreeView(const TreeView&) = delete;
      |   ^~~~~~~~
In file included from vis_03_treeview_with_popup.cpp:11:
vis_03_treeview_with_popup.hpp:16:7: error: use of deleted function 'Glib::ObjectBase::ObjectBase(const Glib::ObjectBase&)'
   16 | class TreeView_WithPopup : public Gtk::TreeView {
      |       ^~~~~~~~~~~~~~~~~~
In file included from /usr/include/glibmm-2.4/glibmm/wrap.h:22,
                 from /usr/include/glibmm-2.4/glibmm/containerhandle_shared.h:24,
                 from /usr/include/glibmm-2.4/glibmm/arrayhandle.h:21,
                 from /usr/include/glibmm-2.4/glibmm.h:92,
                 from /usr/include/gtkmm-3.0/gtkmm.h:87,
                 from vis_03_treeview_with_popup.hpp:11,
                 from vis_03_treeview_with_popup.cpp:11:
/usr/include/glibmm-2.4/glibmm/objectbase.h:61:3: note: declared here
   61 |   ObjectBase(const ObjectBase&) = delete;