it's not easy to get the linking step to pass
there are defines like SOKOL_GLUE_IMPL that will lead to functions
being defined. don't know how to handle that when headers go into
different files

-- Generating done
-- Build files have been written to: /home/martin/stage/cl-cpp-generator2/example/72_emsdk/03source/b
[4/4] Linking CXX executable index.html
FAILED: index.html
: && /home/martin/src/emsdk/upstream/emscripten/em++ -g  -ggdb -O0  CMakeFiles/index.dir/SokolApp.cpp.o CMakeFiles/index.dir/SokolAppImpl.cpp.o CMakeFiles/index.dir/index.cpp.o -o index.html   && :
wasm-ld: error: duplicate symbol: sapp_sgcontext
>>> defined in CMakeFiles/index.dir/SokolApp.cpp.o
>>> defined in CMakeFiles/index.dir/SokolAppImpl.cpp.o

wasm-ld: error: duplicate symbol: __em_js__simgui_js_is_osx
>>> defined in CMakeFiles/index.dir/SokolApp.cpp.o
>>> defined in CMakeFiles/index.dir/SokolAppImpl.cpp.o