i don't know how to introduce the semantics to capture a variable
from a c++ lambda

render_00_main.cpp:40:21: error: variable 'app' cannot be implicitly captured in a lambda with no capture-default specified