looks like stdc++ nano supports neither format nor sstream
v-none-elf/bin/ld: removing unused section '.text._open' in file '/home/martin/risc/xpack-riscv-none-elf-gcc-13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/lib/libnosys.a(open.o)'
/home/martin/risc/xpack-riscv-none-elf-gcc-13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/bin/ld: removing unused section '.comment' in file '/home/martin/risc/xpack-riscv-none-elf-gcc-13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/lib/libnosys.a(open.o)'
/home/martin/risc/xpack-riscv-none-elf-gcc-13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/bin/ld: removing unused section '.riscv.attributes' in file '/home/martin/risc/xpack-riscv-none-elf-gcc-13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/lib/libnosys.a(open.o)'
/home/martin/risc/xpack-riscv-none-elf-gcc-13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/bin/ld: removing unused section '.eh_frame' in file '/tmp/ccQ7k3nQ.ltrans0.ltrans.o'
/home/martin/risc/xpack-riscv-none-elf-gcc-13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/bin/ld: removing unused section '.group' in file '/tmp/ccQ7k3nQ.ltrans1.ltrans.o'
/home/martin/risc/xpack-riscv-none-elf-gcc-13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/bin/ld: removing unused section '.sbss' in file '/tmp/ccQ7k3nQ.ltrans1.ltrans.o'
/home/martin/risc/xpack-riscv-none-elf-gcc-13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/bin/ld: removing unused section '.sdata.DW.ref.__gcc_personality_v0[DW.ref.__gcc_personality_v0]' in file '/tmp/ccQ7k3nQ.ltrans1.ltrans.o'
/home/martin/risc/xpack-riscv-none-elf-gcc-13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/bin/ld: removing unused section '.eh_frame' in file '/tmp/ccQ7k3nQ.ltrans1.ltrans.o'
/home/martin/risc/xpack-riscv-none-elf-gcc-13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/bin/ld: removing unused section '.eh_frame' in file '/home/martin/risc/xpack-riscv-none-elf-gcc-13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/libgcc.a(unwind-c.o)'
/home/martin/risc/xpack-riscv-none-elf-gcc-13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/bin/ld: warning: risc_usb_test has a LOAD segment with RWX permissions
/home/martin/risc/xpack-riscv-none-elf-gcc-13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/bin/ld: /home/martin/risc/xpack-riscv-none-elf-gcc-13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/lib/libstdc++_nano.a(globals_io.o): in function `.L0 ':
(.text.startup._GLOBAL__sub_I.00090__ZSt3cin+0xc): undefined reference to `__dso_handle'
/home/martin/risc/xpack-riscv-none-elf-gcc-13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/bin/ld: /home/martin/risc/xpack-riscv-none-elf-gcc-13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/lib/libstdc++_nano.a(ios_errcat.o): in function `_GLOBAL__sub_I__ZSt17iostream_categoryv':
(.text.startup._GLOBAL__sub_I__ZSt17iostream_categoryv+0x0): undefined reference to `__dso_handle'
/home/martin/risc/xpack-riscv-none-elf-gcc-13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/bin/ld: /home/martin/risc/xpack-riscv-none-elf-gcc-13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/lib/libstdc++_nano.a(system_error.o): in function `.L0 ':
(.text.startup._GLOBAL__sub_I__ZSt20__throw_system_errori+0x2): undefined reference to `__dso_handle'
/home/martin/risc/xpack-riscv-none-elf-gcc-13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/bin/ld: (.text.startup._GLOBAL__sub_I__ZSt20__throw_system_errori+0x1e): undefined reference to `__dso_handle'
/home/martin/risc/xpack-riscv-none-elf-gcc-13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/bin/ld: risc_usb_test: hidden symbol `__dso_handle' isn't defined
/home/martin/risc/xpack-riscv-none-elf-gcc-13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status