here is the output of trying to compile cudacpp with clang or g++
martin@labolg ~/src/cudacpp/examples $ clang++  -I../include -DNVRTC_GET_TYPE_NAME=1  -DFIXED_GRID_INDEX -I /media/sdb4/cuda/11.0.1/include/  -std=c++20 invoke-rtc.cpp main.cpp
In file included from invoke-rtc.cpp:4:
In file included from ../include/cudacpp/rtc/Program.h:140:
../include/cudacpp/rtc/Kernel.h:69:31: error: unknown type name 'Stream'
        CUresult launchAndWait(const Stream& stream, const ARGS& ...args) {
                                     ^
../include/cudacpp/rtc/Kernel.h:143:3: error: call to function 'AddTypesToTemplate' that is neither visible in the template definition nor found by argument-dependent lookup
                AddTypesToTemplate<U, REST...>(params);
                ^
../include/cudacpp/rtc/Kernel.h:172:10: note: in instantiation of function template specialization 'cudacpp::rtc::detail::AddTypesToTemplate<float, std::integral_constant<int, 10>>' requested here
        detail::AddTypesToTemplate<ARGS...>(tp);
                ^
invoke-rtc.cpp:21:41: note: in instantiation of function template specialization 'cudacpp::rtc::Kernel::instantiate<float, std::integral_constant<int, 10> >' requested here
        auto kernel = rtc::Kernel("setKernel").instantiate<float, std::integral_constant<int, 10>>();
                                               ^
../include/cudacpp/rtc/Kernel.h:147:21: note: 'AddTypesToTemplate' should be declared prior to the call site or in namespace 'cudacpp::rtc'
        static inline void AddTypesToTemplate(Kernel::TemplateParameters& params) {
                           ^
2 errors generated.
martin@labolg ~/src/cudacpp/examples $ g++  -I../include -DNVRTC_GET_TYPE_NAME=1  -DFIXED_GRID_INDEX -I /media/sdb4/cuda/11.0.1/include/  -std=c++20 invoke-rtc.cpp main.cpp
In file included from ../include/cudacpp/rtc/Program.h:140,
                 from invoke-rtc.cpp:4:
../include/cudacpp/rtc/Kernel.h:69:31: error: 'Stream' does not name a type; did you mean 'CUstream'?
   69 |  CUresult launchAndWait(const Stream& stream, const ARGS& ...args) {
      |                               ^~~~~~
      |                               CUstream
../include/cudacpp/rtc/Kernel.h: In member function 'CUresult cudacpp::rtc::Kernel::launchAndWait(const int&, const ARGS& ...)':
../include/cudacpp/rtc/Kernel.h:74:17: error: request for member 'synchronize' in 'stream', which is of non-class type 'const int'
   74 |   return stream.synchronize();
      |                 ^~~~~~~~~~~
../include/cudacpp/rtc/Kernel.h: In instantiation of 'auto cudacpp::rtc::detail::AddTypesToTemplate(cudacpp::rtc::Kernel::TemplateParameters&) [with T = float; U = std::integral_constant<int, 10>; REST = {}]':
../include/cudacpp/rtc/Kernel.h:172:37:   required from 'cudacpp::rtc::Kernel& cudacpp::rtc::Kernel::instantiate() [with ARGS = {float, std::integral_constant<int, 10>}]'
invoke-rtc.cpp:21:93:   required from here
../include/cudacpp/rtc/Kernel.h:143:33: error: no matching function for call to 'AddTypesToTemplate<std::integral_constant<int, 10> >(cudacpp::rtc::Kernel::TemplateParameters&)'
  143 |   AddTypesToTemplate<U, REST...>(params);
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
../include/cudacpp/rtc/Kernel.h:141:21: note: candidate: 'template<class T, class U, class ... REST> auto cudacpp::rtc::detail::AddTypesToTemplate(cudacpp::rtc::Kernel::TemplateParameters&)'
  141 |  static inline auto AddTypesToTemplate(Kernel::TemplateParameters& params) {
      |                     ^~~~~~~~~~~~~~~~~~
../include/cudacpp/rtc/Kernel.h:141:21: note:   template argument deduction/substitution failed:
../include/cudacpp/rtc/Kernel.h:143:33: note:   couldn't deduce template parameter 'U'
  143 |   AddTypesToTemplate<U, REST...>(params);
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~