refactor: remove unused load statement from BUILD file
 $ bazel build //:main
INFO: Analyzed target //:main (69 packages loaded, 483 targets configured).
ERROR: /home/kiel/stage/cl-cpp-generator2/example/189_bazel_tutorial/bazel_tutorial/BUILD:10:10: Compiling cc/main.cpp failed: (Exit 1): gcc failed: error executing CppCompile command (from target //:main) /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++17' -MD -MF bazel-out/k8-fastbuild/bin/_objs/main/main.pic.d ... (remaining 19 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
cc/main.cpp:1:10: fatal error: cc/my_lib/my_lib.hpp: No such file or directory
    1 | #include "cc/my_lib/my_lib.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Target //:main failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 11.342s, Critical Path: 0.07s
INFO: 7 processes: 6 internal, 1 linux-sandbox.
ERROR: Build did NOT complete successfully