i made some steps towards getting aruco to build
but its still not working

--     Linker flags (Release):      -Wl,--gc-sections -O2
--     Linker flags (Debug):        -Wl,--gc-sections
--     ccache:                      YES
--     Precompiled headers:         NO
--     Extra dependencies:
--     3rdparty dependencies:       zlib libprotobuf quirc
--
--   OpenCV modules:
--     To be built:                 calib3d core dnn features2d flann imgproc js objdetect photo video
--     Disabled:                    highgui imgcodecs ml stitching videoio world
--     Disabled by dependency:      ts
--     Unavailable:                 gapi java python2 python3
--     Applications:                examples
--     Documentation:               js
--     Non-free algorithms:         NO
--
--   GUI:
--
--   Media I/O:
--     ZLib:                        build (ver 1.2.11)
--     JPEG 2000:                   build (ver 2.4.0)
--     HDR:                         YES
--     SUNRASTER:                   YES
--     PXM:                         YES
--     PFM:                         YES
--
--   Video I/O:
--
--   Parallel framework:            pthreads
--
--   Other third-party libraries:
--     VA:                          NO
--     Custom HAL:                  NO
--     Protobuf:                    build (3.19.1)
--
--   Python (for build):            /usr/bin/python
--
--   Install to:                    /usr/local

See also "/home/martin/src/opencv/build_wasm/CMakeFiles/CMakeOutput.log".
See also "/home/martin/src/opencv/build_wasm/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "/home/martin/src/opencv/./platforms/js/build_js.py", line 288, in <module>
    builder.config()
  File "/home/martin/src/opencv/./platforms/js/build_js.py", line 200, in config
    execute(cmd)
  File "/home/martin/src/opencv/./platforms/js/build_js.py", line 23, in execute
    raise Fail("Child returned: %s" % retcode)
__main__.Fail: Child returned: 1

Build output check failed:
    Regex: 'unknown .*option'
    Output line: 'warning: unknown warning option '-Wno-cast-function-type', did you mean '-Wno-bad-function-cast'? [-Wunknown-warning-option]'
Compilation failed:
    source file: '/home/martin/src/opencv/build_wasm/CMakeFiles/CMakeTmp/src.c'
    check option: ' -Wno-cast-function-type'
===== BUILD LOG =====
Change Dir: /home/martin/src/opencv/build_wasm/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_031ab/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_031ab.dir/build.make CMakeFiles/cmTC_031ab.dir/build
gmake[1]: Entering directory '/home/martin/src/opencv/build_wasm/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_031ab.dir/src.c.o
/home/martin/src/emsdk/upstream/emscripten/emcc   -s WASM=1 -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=4 -msimd128    -fsigned-char -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winconsistent-missing-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -Wno-deprecated-enum-enum-conversion -Wno-deprecated-anon-enum-enum-conversion -fdiagnostics-show-option -pthread -Qunused-arguments -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -Wno-implicit-const-int-float-conversion -Wno-undef -Wno-strict-prototypes  -DNDEBUG -O2  -DNDEBUG    -Wno-cast-function-type -o CMakeFiles/cmTC_031ab.dir/src.c.o -c /home/martin/src/opencv/build_wasm/CMakeFiles/CMakeTmp/src.c
warning: unknown warning option '-Wno-cast-function-type'; did you mean '-Wno-bad-function-cast'? [-Wunknown-warning-option]
/home/martin/src/opencv/build_wasm/CMakeFiles/CMakeTmp/src.c:1:8: warning: unknown pragma ignored [-Wunknown-pragmas]
       ^
2 warnings generated.
Linking C executable cmTC_031ab.js
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_031ab.dir/link.txt --verbose=1
/home/martin/src/emsdk/upstream/emscripten/emcc -s WASM=1 -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=4 -msimd128    -fsigned-char -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winconsistent-missing-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -Wno-deprecated-enum-enum-conversion -Wno-deprecated-anon-enum-enum-conversion -fdiagnostics-show-option -pthread -Qunused-arguments -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -Wno-implicit-const-int-float-conversion -Wno-undef -Wno-strict-prototypes  -DNDEBUG -O2  -DNDEBUG   -Wl,--gc-sections  -O2 @CMakeFiles/cmTC_031ab.dir/objects1.rsp -o cmTC_031ab.js
gmake[1]: Leaving directory '/home/martin/src/opencv/build_wasm/CMakeFiles/CMakeTmp'

: