maybe i shouldn't define signal functions
vis_02_dialog.cpp:51:73: warning: 'void QComboBox::currentIndexChanged(const QString&)' is deprecated: Use currentIndexChanged(int) instead, and get the text using itemText(index) -Wdeprecated-declarations]
   51 |           QOverload<const QString &>::of(&QComboBox::currentIndexChanged), this,
      |                                                                         ^
In file included from /usr/include/qt5/QtWidgets/QComboBox:1,
                 from vis_02_dialog.cpp:9:
/usr/include/qt5/QtWidgets/qcombobox.h:240:10: note: declared here
  240 |     void currentIndexChanged(const QString &);
      |          ^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/qt5/QtGui/qtguiglobal.h:43,
                 from /usr/include/qt5/QtWidgets/qtwidgetsglobal.h:43,
                 from /usr/include/qt5/QtWidgets/qapplication.h:43,
                 from /usr/include/qt5/QtWidgets/QApplication:1,
                 from vis_01_serial.hpp:7,
                 from vis_02_dialog.cpp:7:
/usr/include/qt5/QtCore/qobject.h: In instantiation of 'static QMetaObject::Connection QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, const typename QtPrivate::FunctionPointer<Func2>::Object*, Func2, Qt::ConnectionType) [with Func1 = void (SerialReaderThread::*)(const QString&); Func2 = void (Dialog::*)(QString&); typename QtPrivate::FunctionPointer<Func>::Object = SerialReaderThread; typename QtPrivate::FunctionPointer<Func2>::Object = Dialog]':
vis_02_dialog.cpp:46:78:   required from here
/usr/include/qt5/QtCore/qobject.h:255:9: error: static assertion failed: Signal and slot arguments are not compatible.
  255 |         Q_STATIC_ASSERT_X((QtPrivate::CheckCompatibleArguments<typename SignalType::Arguments, typename SlotType::Arguments>::value),
      |         ^~~~~~~~~~~~~~~~~
make: *** [Makefile:530: vis_02_dialog.o] Error 1