i think i'm still missing some binding code
>>> [vertex.point for vertex in cdt.finite_vertices()]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
TypeError: Unable to convert function return value to a Python type! The signature was
        (self: pybind11_builtins.iterator) -> CGAL::Delaunay_mesh_vertex_base_2<CGAL::Epick, CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<CGAL::Triangulation_data_structure_2<CGAL::Delaunay_mesh_vertex_base_2<CGAL::Epick, CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> > >, CGAL::Delaunay_mesh_face_base_2<CGAL::Epick, CGAL::Constrained_Delaunay_triangulation_face_base_2<CGAL::Epick, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick, CGAL::Triangulation_face_base_2<CGAL::Epick, CGAL::Triangulation_ds_face_base_2<void> > > > > > > > >