what does this error mean?
is the client connection complaining about server_interface?

g++ -c -o simple_00_client.o simple_00_client.cpp -O0 -g3 -ggdb -std=gnu++17 -Wall -Wextra -Werror -Wfatal-errors -ffunction-sections -fdata-sections -Wno-error=unused-variable -Wno-error=unused-parameter -Wno-error=double-promotion -pipe -march=native -mtune=native -DASIO_STANDALONE
In file included from simple_00_client.hpp:17,
                 from simple_00_client.cpp:16:
vis_03_connection.hpp: In instantiation of ‘void connection<T>::connect_to_server(const results_type&) [with T = CustomMsgTypes; boost::asio::ip::basic_resolver<boost::asio::ip::tcp>::results_type = boost::asio::ip::basic_resolver_results<boost::asio::ip::tcp>]’:
vis_04_client.hpp:27:38:   required from ‘bool client_interface<T>::connect(const string&, uint16_t) [with T = CustomMsgTypes; std::string = std::__cxx11::basic_string<char>; uint16_t = short unsigned int]’
simple_00_client.cpp:46:31:   required from here
vis_03_connection.hpp:66:69: warning: unused parameter ‘endpoint’ [-Wunused-parameter]
   66 |           [this](std::error_code ec, boost::asio::ip::tcp::endpoint endpoint) {
      |                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
vis_03_connection.hpp: In instantiation of ‘void connection<T>::write_header() [with T = CustomMsgTypes]’:
vis_03_connection.hpp:80:9:   required from ‘void connection<T>::send(const message<T>&) [with T = CustomMsgTypes]’
vis_04_client.hpp:63:25:   required from ‘void client_interface<T>::send(const message<T>&) [with T = CustomMsgTypes]’
simple_00_client.cpp:22:11:   required from here
vis_03_connection.hpp:145:48: warning: unused parameter ‘length’ [-Wunused-parameter]
  145 |         [this](std::error_code ec, std::size_t length) {
      |                                    ~~~~~~~~~~~~^~~~~~
vis_03_connection.hpp: In instantiation of ‘void connection<T>::read_validation(server_interface<T>*) [with T = CustomMsgTypes]’:
vis_03_connection.hpp:68:15:   required from ‘void connection<T>::connect_to_server(const results_type&) [with T = CustomMsgTypes; boost::asio::ip::basic_resolver<boost::asio::ip::tcp>::results_type = boost::asio::ip::basic_resolver_results<boost::asio::ip::tcp>]’
vis_04_client.hpp:27:38:   required from ‘bool client_interface<T>::connect(const string&, uint16_t) [with T = CustomMsgTypes; std::string = std::__cxx11::basic_string<char>; uint16_t = short unsigned int]’
simple_00_client.cpp:46:31:   required from here
vis_03_connection.hpp:252:23: error: invalid use of incomplete type ‘class server_interface<CustomMsgTypes>’
  252 |               server->on_client_validated(this->shared_from_this());
      |               ~~~~~~~~^~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
make: *** [makefile:39: simple_00_client.o] Error 1