what is wrong here?
martin@labolg ~/stage/cl-cpp-generator2/example/19_nvrtc/source $ make
c++ -O0 -march=native -Wall -std=gnu++20 -I/media/sdb4/cuda/11.0.1/include/ -DNVRTC_GET_TYPE_NAME=1 -L/media/sdb4/cuda/11.0.1/lib -lcudart -lcuda -lnvrtc -o vis vis_00_main.cpp
vis_00_main.cpp: In function 'int main()':
vis_00_main.cpp:44:8: warning: variable 'program' set but not used [-Wunused-but-set-variable]
   44 |   auto program = Program("myprog", code);
      |        ^~~~~~~
In file included from vis_00_main.cpp:10:
vis_01_rtc.cpp: In instantiation of 'auto detail::AddTypesToTemplate(Kernel::TemplateParameters&) [with T = float; U = std::integral_constant<int, 10>; REST = {}]':
vis_01_rtc.cpp:143:38:   required from 'Kernel& Kernel::instantiate() [with ARGS = {float, std::integral_constant<int, 10>}]'
vis_00_main.cpp:46:79:   required from here
vis_01_rtc.cpp:133:33: error: no matching function for call to 'AddTypesToTemplate<std::integral_constant<int, 10> >(Kernel::TemplateParameters&)'
  133 |   AddTypesToTemplate<U, REST...>(params);
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
vis_01_rtc.cpp:131:20: note: candidate: 'template<class T, class U, class ... REST> auto detail::AddTypesToTemplate(Kernel::TemplateParameters&)'
  131 | static inline auto AddTypesToTemplate(Kernel::TemplateParameters &params) {
      |                    ^~~~~~~~~~~~~~~~~~
vis_01_rtc.cpp:131:20: note:   template argument deduction/substitution failed:
vis_01_rtc.cpp:133:33: note:   couldn't deduce template parameter 'U'
  133 |   AddTypesToTemplate<U, REST...>(params);