why this error?
file included from simple_01_server.hpp:18,
                 from simple_01_server.cpp:7:
vis_05_server.hpp: In instantiation of ‘void server_interface<T>::update(size_t, bool) [with T = CustomMsgTypes; size_t = long unsigned int]’:
simple_01_server.cpp:94:27:   required from here
vis_05_server.hpp:159:39: error: no matching function for call to ‘tsqueue<owned_message<CustomMsgTypes> >::wait_while_empty()’
  159 |       m_q_messages_in.wait_while_empty();
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
compilation terminated due to -Wfatal-errors.