i can't just push all the class prototypes into proto2.h
CudaContext is defined in 02 but used in 01

c++ -c -o vis_00_main.o vis_00_main.cpp -O0 -march=native -Wall -std=gnu++20 -I/media/sdb4/cuda/11.0.1/include/ -DNVRTC_GET_TYPE_NAME=1
In file included from globals.h:5,
                 from vis_00_main.cpp:4:
proto2.h:32:24: error: 'CudaContext' does not name a type; did you mean 'CUcontext'?
   32 |          Module (const CudaContext& ctx, const Program& p);
      |                        ^~~~~~~~~~~
      |                        CUcontext
proto2.h:32:48: error: 'Program' does not name a type
   32 |          Module (const CudaContext& ctx, const Program& p);
      |                                                ^~~~~~~
proto2.h:53:43: error: 'Program' does not name a type