i don't understand this error:
vis_03_connection.hpp: In instantiation of ‘void connection<T>::send(const message<T>&) const [with T = CustomMsgTypes]’:
vis_04_client.hpp:58:55:   required from ‘void client_interface<T>::send(const message<T>&) [with T = CustomMsgTypes]’
simple_00_client.cpp:26:11:   required from here
vis_03_connection.hpp:56:78: error: passing ‘const tsqueue<message<CustomMsgTypes> >’ as ‘this’ argument discards qualifiers [-fpermissive]
   56 |                                     const auto idle  = m_q_messages_out.empty();
      |                                                        ~~~~~~~~~~~~~~~~~~~~~~^~
In file included from simple_00_client.hpp:16,
                 from simple_00_client.cpp:7:
vis_02_tsqueue.hpp:33:14: note:   in call to ‘bool tsqueue<T>::empty() [with T = message<CustomMsgTypes>]’
   33 |         bool empty ()    {