more errors
c++ -c -o vis_04_decode_packet.o vis_04_decode_packet.cpp -Os -g3 -ggdb -Wall -Wextra -Werror -Wshadow -Wdouble-promotion -fno-common -Wconversion -ffunction-sections -fdata-sections -Wno-error=unused-variable -pipe `pkg-config gtkmm-3.0 --cflags` -march=native -mtune=native
vis_04_decode_packet.cpp: In function 'int init_decode_packet(int, std::complex<float>*)':
vis_04_decode_packet.cpp:287:50: error: conversion from 'int' to 'float' may change value [-Werror=conversion]
  287 |       static_cast<int>(round(ceil((((((2.0f)) * (number_of_quads))) / (256)))));
      |                                                 ~^~~~~~~~~~~~~~~~
vis_04_decode_packet.cpp:292:72: error: conversion from 'int' to 'float' may change value [-Werror=conversion]
  292 |   auto swst = ((((((0x1) * (header[55]))) + (((0x100) * (header[54]))) +
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
  293 |                  (((0x10000) * (((0xFF) & (header[53]))))))) /
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
vis_04_decode_packet.cpp:295:42: error: implicit conversion from 'float' to 'double' to match other operand of binary expression [-Werror=double-promotion]
  295 |   auto delta_t_suppressed = (((3.20e+2)) / (((8) * (fref))));
      |                              ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
vis_04_decode_packet.cpp:296:32: error: implicit conversion from 'float' to 'double' to match other operand of binary expression [-Werror=double-promotion]