need to define a backend
In file included from ../SokolApp.cpp:16:
/home/martin/src/sokol/util/sokol_imgui.h:1592:2: error: "Please define one of SOKOL_GLCORE33, SOKOL_GLES2, SOKOL_GLES3, SOKOL_D3D11, SOKOL_METAL, SOKOL_WGPU or SOKOL_DUMMY_BACKEND!"
 ^