it was working for a bit but now
the virtual is messing up the cpp

g++ -c -o simple_01_server.o simple_01_server.cpp -Og -g3 -ggdb -std=gnu++17 -Wall -Wextra -Werror -Wfatal-errors -ffunction-sections -fdata-sections -Wno-error=unused-variable -Wno-error=unused-parameter -Wno-error=double-promotion -pipe -march=native -mtune=native -DASIO_STANDALONE
simple_01_server.cpp:19:1: error: ‘virtual’ outside class declaration
   19 | virtual bool CustomServer::on_client_connect(