i enabled more code and now it complains again about the gl log stuff
usr/bin/ld: removing unused section '.text._ZNK12SkRefCntBase9getRefCntEv[_ZNK12SkRefCntBase9getRefCntEv]' in file 'GrGLInterfaceAutogen.o'
/usr/bin/ld: removing unused section '.text.__clang_call_terminate[__clang_call_terminate]' in file 'GrGLInterfaceAutogen.o'
/usr/bin/ld: removing unused section '.text._ZStanSt12memory_orderSt23__memory_order_modifier[_ZStanSt12memory_orderSt23__memory_order_modifier]' in file 'GrGLInterfaceAutogen.o'
[martin@localhost source]$ ./vis
1605341823542889491 140239414881984 vis_00_base.cpp:28 main start   argc='1' argv[0]='./vis'
1605341823686691688 140239414881984 vis_00_base.cpp:100 main   windowFormat='370546692' contextType='0'    dw='512'    dh='200'
1605341823686715172 140239414881984 vis_00_base.cpp:110 main   SDL_GetPixelFormatName(windowFormat)='SDL_PIXELFORMAT_RGB888'
---- glGetError 0x500(Invalid Enum) at
        GrGLUtil.cpp(566) :
                GetString(0x1F02)
nullptr GL version string.GrGLInterfaceAutogen.cpp:86 GrGLInterface::validate() failed.
vis_00_base.cpp:120: fatal error: "assert(grContext)"
Aborted (core dumped)
[martin@localhost source]$ ls
globals.h                 GrGLInterfaceAutogen.o  GrGLUtil.o  utils.h  vis_00_base.cpp  vis_00_base.o
GrGLInterfaceAutogen.cpp  GrGLUtil.cpp            makefile    vis      vis_00_base.hpp