add more arpack++ boilerplate code
martin@labolg ~/stage/cl-cpp-generator2/example/27_sparse_eigen_hydrogen/source $ make
/media/sdb4/cuda/11.0.1/cuda_nvcc/bin/nvcc -c -o vis_00_cuda_main.o vis_00_cuda_main.cu --gpu-architecture=compute_75 --gpu-code=compute_75 -use_fast_math -ftz=true --std=c++17 -O1 -g -Xcompiler=-march=native --compiler-bindir=/usr/x86_64-pc-linux-gnu/gcc-bin/8.4.0 -I/media/sdb4/cuda/11.0.1/include -Iarpack-ng/b/
arpackpp/include/arrssym.h(64): warning: function "ARrcStdEig<ARFLOAT, ARTYPE>::Trace() [with ARFLOAT=float, ARTYPE=float]" is hidden by "ARrcSymStdEig<ARFLOAT>::Trace [with ARFLOAT=float]" -- virtual function override intended?
          detected during instantiation of class "ARrcSymStdEig<ARFLOAT> [with ARFLOAT=float]"
vis_00_cuda_main.cu(80): here

arpackpp/include/arrssym.h(64): warning: function "ARrcStdEig<ARFLOAT, ARTYPE>::Trace() [with ARFLOAT=float, ARTYPE=float]" is hidden by "ARrcSymStdEig<ARFLOAT>::Trace [with ARFLOAT=float]" -- virtual function override intended?
          detected during instantiation of class "ARrcSymStdEig<ARFLOAT> [with ARFLOAT=float]"
vis_00_cuda_main.cu(80): here

/media/sdb4/cuda/11.0.1/cuda_nvcc/bin/nvcc -o vis_00_cuda_main vis_00_cuda_main.o --gpu-architecture=compute_75 --gpu-code=compute_75 -use_fast_math -ftz=true --std=c++17 -O1 -g -Xcompiler=-march=native --compiler-bindir=/usr/x86_64-pc-linux-gnu/gcc-bin/8.4.0 -I/media/sdb4/cuda/11.0.1/include -Iarpack-ng/b/ -L/media/sdb4/cuda/11.0.1/lib -L/media/sdb4/cuda/11.0.1/cuda_cudart/targets/x86_64-linux/lib -Larpack-ng/b/ -larpack -llapack -lblas
/usr/lib/gcc/x86_64-pc-linux-gnu/8.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: arpack-ng/b//libarpack.a(ssaupd.f.o): undefined reference to symbol '_gfortran_transfer_real_write@@GFORTRAN_8'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/libgfortran.so.5: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [makefile:23: vis_00_cuda_main] Error 1